import { jsPDF } from "jspdf";
import type { VerificationRecord } from "./verification-queue";

/**
 * Renders an "official" JustAsk lawyer verification summary as a
 * client-generated PDF. Kept English-only for a stable document look
 * regardless of app language (Hebrew PDF requires embedding a Unicode font).
 */
export function exportVerificationPdf(rec: VerificationRecord) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 56;
  let y = margin;

  // Header band
  doc.setFillColor(15, 23, 42); // navy
  doc.rect(0, 0, pageW, 96, "F");
  doc.setTextColor(212, 175, 55); // gold
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("JUSTASK  ·  LEGAL CONCIERGE", margin, 42);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("Lawyer verification summary", margin, 70);

  y = 128;

  // Meta line
  doc.setTextColor(90, 90, 90);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const submitted = new Date(rec.submittedAt).toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Reference: ${rec.id}`, margin, y);
  doc.text(`Submitted: ${submitted}`, pageW - margin, y, { align: "right" });
  y += 24;

  // Divider
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(1);
  doc.line(margin, y, pageW - margin, y);
  y += 28;

  const rows: [string, string][] = [
    ["Full name", rec.fullName || "—"],
    ["National ID (T.Z.)", rec.idNumber || "—"],
    ["Email", rec.email || "—"],
    ["Phone", rec.phone || "—"],
    ["Bar license", rec.barNumber ? `#${rec.barNumber} · ${rec.barYear}` : "—"],
    ["Education", rec.university ? `${rec.university} · ${rec.gradYear}` : "—"],
    ["Specialties", formatSpecialties(rec)],
    ["Status", rec.status.toUpperCase()],
  ];

  doc.setFontSize(11);
  for (const [label, value] of rows) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const wrapped = doc.splitTextToSize(String(value), pageW - margin * 2 - 160);
    doc.text(wrapped, margin + 160, y);
    y += Math.max(20, wrapped.length * 14);
  }

  // Footer
  y = doc.internal.pageSize.getHeight() - 72;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageW - margin, y);
  y += 18;
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This document was generated by JustAsk and reflects data submitted by the applicant.",
    margin,
    y,
  );
  y += 12;
  doc.text(
    "Final approval is issued by the JustAsk verification team after credential review.",
    margin,
    y,
  );

  doc.save(`justask-verification-${rec.id}.pdf`);
}
