/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidatingRouteImport } from './routes/validating'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LawyerSubscriptionRouteImport } from './routes/lawyer-subscription'
import { Route as LawyerOnboardingRouteImport } from './routes/lawyer-onboarding'
import { Route as LawyerRouteImport } from './routes/lawyer'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawyerProfileLawyerIdRouteImport } from './routes/lawyer-profile.$lawyerId'
import { Route as LawyerCaseCaseIdRouteImport } from './routes/lawyer-case.$caseId'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'

const ValidatingRoute = ValidatingRouteImport.update({
  id: '/validating',
  path: '/validating',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerSubscriptionRoute = LawyerSubscriptionRouteImport.update({
  id: '/lawyer-subscription',
  path: '/lawyer-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerOnboardingRoute = LawyerOnboardingRouteImport.update({
  id: '/lawyer-onboarding',
  path: '/lawyer-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRoute = LawyerRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerProfileLawyerIdRoute = LawyerProfileLawyerIdRouteImport.update({
  id: '/lawyer-profile/$lawyerId',
  path: '/lawyer-profile/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerCaseCaseIdRoute = LawyerCaseCaseIdRouteImport.update({
  id: '/lawyer-case/$caseId',
  path: '/lawyer-case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRoute
  IntakeRoute: typeof IntakeRoute
  LawyerRoute: typeof LawyerRoute
  LawyerOnboardingRoute: typeof LawyerOnboardingRoute
  LawyerSubscriptionRoute: typeof LawyerSubscriptionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SubmittedRoute: typeof SubmittedRoute
  ValidatingRoute: typeof ValidatingRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
  LawyerCaseCaseIdRoute: typeof LawyerCaseCaseIdRoute
  LawyerProfileLawyerIdRoute: typeof LawyerProfileLawyerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validating': {
      id: '/validating'
      path: '/validating'
      fullPath: '/validating'
      preLoaderRoute: typeof ValidatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-subscription': {
      id: '/lawyer-subscription'
      path: '/lawyer-subscription'
      fullPath: '/lawyer-subscription'
      preLoaderRoute: typeof LawyerSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-onboarding': {
      id: '/lawyer-onboarding'
      path: '/lawyer-onboarding'
      fullPath: '/lawyer-onboarding'
      preLoaderRoute: typeof LawyerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer': {
      id: '/lawyer'
      path: '/lawyer'
      fullPath: '/lawyer'
      preLoaderRoute: typeof LawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-profile/$lawyerId': {
      id: '/lawyer-profile/$lawyerId'
      path: '/lawyer-profile/$lawyerId'
      fullPath: '/lawyer-profile/$lawyerId'
      preLoaderRoute: typeof LawyerProfileLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-case/$caseId': {
      id: '/lawyer-case/$caseId'
      path: '/lawyer-case/$caseId'
      fullPath: '/lawyer-case/$caseId'
      preLoaderRoute: typeof LawyerCaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRoute,
  IntakeRoute: IntakeRoute,
  LawyerRoute: LawyerRoute,
  LawyerOnboardingRoute: LawyerOnboardingRoute,
  LawyerSubscriptionRoute: LawyerSubscriptionRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SubmittedRoute: SubmittedRoute,
  ValidatingRoute: ValidatingRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
  LawyerCaseCaseIdRoute: LawyerCaseCaseIdRoute,
  LawyerProfileLawyerIdRoute: LawyerProfileLawyerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
