/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ValidatingRouteImport } from './routes/validating'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LawyerSubscriptionRouteImport } from './routes/lawyer-subscription'
import { Route as LawyerOnboardingRouteImport } from './routes/lawyer-onboarding'
import { Route as LawyerRouteImport } from './routes/lawyer'
import { Route as IntakeTipsRouteImport } from './routes/intake-tips'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTermsRouteImport } from './routes/settings.terms'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsHelpRouteImport } from './routes/settings.help'
import { Route as SettingsAccessibilityRouteImport } from './routes/settings.accessibility'
import { Route as LawyerProfileLawyerIdRouteImport } from './routes/lawyer-profile.$lawyerId'
import { Route as LawyerCaseCaseIdRouteImport } from './routes/lawyer-case.$caseId'
import { Route as CaseCaseIdRouteImport } from './routes/case.$caseId'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatingRoute = ValidatingRouteImport.update({
  id: '/validating',
  path: '/validating',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerSubscriptionRoute = LawyerSubscriptionRouteImport.update({
  id: '/lawyer-subscription',
  path: '/lawyer-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerOnboardingRoute = LawyerOnboardingRouteImport.update({
  id: '/lawyer-onboarding',
  path: '/lawyer-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRoute = LawyerRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeTipsRoute = IntakeTipsRouteImport.update({
  id: '/intake-tips',
  path: '/intake-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/settings/terms',
  path: '/settings/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: '/settings/accessibility',
  path: '/settings/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerProfileLawyerIdRoute = LawyerProfileLawyerIdRouteImport.update({
  id: '/lawyer-profile/$lawyerId',
  path: '/lawyer-profile/$lawyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerCaseCaseIdRoute = LawyerCaseCaseIdRouteImport.update({
  id: '/lawyer-case/$caseId',
  path: '/lawyer-case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCaseIdRoute = CaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/intake-tips': typeof IntakeTipsRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/welcome': typeof WelcomeRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/intake-tips': typeof IntakeTipsRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/welcome': typeof WelcomeRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRoute
  '/intake': typeof IntakeRoute
  '/intake-tips': typeof IntakeTipsRoute
  '/lawyer': typeof LawyerRoute
  '/lawyer-onboarding': typeof LawyerOnboardingRoute
  '/lawyer-subscription': typeof LawyerSubscriptionRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/submitted': typeof SubmittedRoute
  '/validating': typeof ValidatingRoute
  '/welcome': typeof WelcomeRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/case/$caseId': typeof CaseCaseIdRoute
  '/lawyer-case/$caseId': typeof LawyerCaseCaseIdRoute
  '/lawyer-profile/$lawyerId': typeof LawyerProfileLawyerIdRoute
  '/settings/accessibility': typeof SettingsAccessibilityRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/intake-tips'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/welcome'
    | '/admin/verifications'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
    | '/settings/accessibility'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/intake-tips'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/welcome'
    | '/admin/verifications'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
    | '/settings/accessibility'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cases'
    | '/intake'
    | '/intake-tips'
    | '/lawyer'
    | '/lawyer-onboarding'
    | '/lawyer-subscription'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/submitted'
    | '/validating'
    | '/welcome'
    | '/admin/verifications'
    | '/case/$caseId'
    | '/lawyer-case/$caseId'
    | '/lawyer-profile/$lawyerId'
    | '/settings/accessibility'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRoute
  IntakeRoute: typeof IntakeRoute
  IntakeTipsRoute: typeof IntakeTipsRoute
  LawyerRoute: typeof LawyerRoute
  LawyerOnboardingRoute: typeof LawyerOnboardingRoute
  LawyerSubscriptionRoute: typeof LawyerSubscriptionRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SubmittedRoute: typeof SubmittedRoute
  ValidatingRoute: typeof ValidatingRoute
  WelcomeRoute: typeof WelcomeRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  CaseCaseIdRoute: typeof CaseCaseIdRoute
  LawyerCaseCaseIdRoute: typeof LawyerCaseCaseIdRoute
  LawyerProfileLawyerIdRoute: typeof LawyerProfileLawyerIdRoute
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validating': {
      id: '/validating'
      path: '/validating'
      fullPath: '/validating'
      preLoaderRoute: typeof ValidatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-subscription': {
      id: '/lawyer-subscription'
      path: '/lawyer-subscription'
      fullPath: '/lawyer-subscription'
      preLoaderRoute: typeof LawyerSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-onboarding': {
      id: '/lawyer-onboarding'
      path: '/lawyer-onboarding'
      fullPath: '/lawyer-onboarding'
      preLoaderRoute: typeof LawyerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer': {
      id: '/lawyer'
      path: '/lawyer'
      fullPath: '/lawyer'
      preLoaderRoute: typeof LawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake-tips': {
      id: '/intake-tips'
      path: '/intake-tips'
      fullPath: '/intake-tips'
      preLoaderRoute: typeof IntakeTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/help': {
      id: '/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/accessibility': {
      id: '/settings/accessibility'
      path: '/settings/accessibility'
      fullPath: '/settings/accessibility'
      preLoaderRoute: typeof SettingsAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-profile/$lawyerId': {
      id: '/lawyer-profile/$lawyerId'
      path: '/lawyer-profile/$lawyerId'
      fullPath: '/lawyer-profile/$lawyerId'
      preLoaderRoute: typeof LawyerProfileLawyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-case/$caseId': {
      id: '/lawyer-case/$caseId'
      path: '/lawyer-case/$caseId'
      fullPath: '/lawyer-case/$caseId'
      preLoaderRoute: typeof LawyerCaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$caseId': {
      id: '/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/case/$caseId'
      preLoaderRoute: typeof CaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRoute,
  IntakeRoute: IntakeRoute,
  IntakeTipsRoute: IntakeTipsRoute,
  LawyerRoute: LawyerRoute,
  LawyerOnboardingRoute: LawyerOnboardingRoute,
  LawyerSubscriptionRoute: LawyerSubscriptionRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SubmittedRoute: SubmittedRoute,
  ValidatingRoute: ValidatingRoute,
  WelcomeRoute: WelcomeRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  CaseCaseIdRoute: CaseCaseIdRoute,
  LawyerCaseCaseIdRoute: LawyerCaseCaseIdRoute,
  LawyerProfileLawyerIdRoute: LawyerProfileLawyerIdRoute,
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTermsRoute: SettingsTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
